### ISSUE TITLE
url should not verify if exists

### ISSUE THREAD

**Issue by ljean** [pennersr/django-jhouston#3]
Hello,

Good job. I like this idea. However i had some troubles with the current version. It was hanging my dev server.
I think that the verify_exist option of the UrlField should be disabled.

url = models.URLField(max_length=255, verify_exists=False)

With this change, it work ok.

What do you think?

Best
luc

**Comment by kmike** [comment]
verify_exists is removed in django 1.3.1 and 1.2.6 security updates (essentionally it is now False by default); explicit verify_exists=False issues DeprecationWarning in 1.3.1 and 1.2.6. This mean you're running older django version with security bugs. 

I'm not an author of this package but I think it is better to update django instead of adding support for non-secure django releases.

**Comment by ljean** [comment]
hello, 

Thanks for your message. I missed that. my version was in 1.3. I've upgraded to 1.3.1 and the pb has gone. 

Best
luc
